/*
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 *   https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

package org.entur.netex.conversion.osm.transformer;

import org.rutebanken.netex.model.*;
import org.rutebanken.netex.validation.NeTExValidator;
import org.xml.sax.SAXException;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;

import java.io.IOException;
import java.io.OutputStream;
import java.net.UnknownHostException;
import java.time.LocalDateTime;

import static org.entur.netex.conversion.osm.transformer.OsmToNetexMapper.DEFAULT_VERSION;

public class NetexHelper {

    private final ObjectFactory netexObjectFactory;
    private final Marshaller marshaller;

    public NetexHelper(ObjectFactory netexObjectFactory) {
        this.netexObjectFactory = netexObjectFactory;
        try {
            marshaller = JAXBContext.newInstance(StopPlace.class).createMarshaller();
            marshaller.setSchema(new NeTExValidator().getSchema());
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
        } catch (JAXBException | SAXException | IOException e) {
            throw new RuntimeException(e);
        }
    }

    public void marshalNetex(PublicationDeliveryStructure publicationDeliveryStructure, OutputStream outputStream) {
        try {
            marshaller.marshal(netexObjectFactory.createPublicationDelivery(publicationDeliveryStructure), outputStream);
        } catch (JAXBException e) {
            throw new RuntimeException(e);
        }
    }

    @SuppressWarnings("unchecked")
    public PublicationDeliveryStructure createPublicationDelivery(SiteFrame siteFrame, String generatedFrom, String participantRef) {
        return new PublicationDeliveryStructure()
                .withPublicationTimestamp(LocalDateTime.now())
                .withDescription(new MultilingualString()
                        .withValue(generatePublicationDeliveryDescription(generatedFrom)))
                .withParticipantRef(participantRef)
                .withDataObjects(new PublicationDeliveryStructure.DataObjects()
                        .withCompositeFrameOrCommonFrame(netexObjectFactory.createSiteFrame(siteFrame)));
    }

    public <ZONE extends Zone_VersionStructure> ZONE createNetexObject(Class<ZONE> clazz) {
        try {
            return clazz.getConstructor().newInstance();
        } catch (Exception e) {
            throw new IllegalArgumentException("Cannot create class from class name: " + clazz, e);
        }
    }


    private String generatePublicationDeliveryDescription(String osmInput) {
        return String.format("Generated by osm-to-netex on host : %s from input %s. Tool: https://github.com/entur/osm-to-netex", hostname(), osmInput);
    }

    private String hostname() {

        try {
            return java.net.InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            System.err.println("Cannot detect hostname for this computer " + e.getMessage());
        }

        return "unknown";
    }

    public SiteFrame createSiteFrame() {
        SiteFrame siteFrame = new SiteFrame();
        siteFrame.setVersion(DEFAULT_VERSION);
        siteFrame.setId("OSM:SiteFrame:" + System.currentTimeMillis());
        siteFrame.setCreated(LocalDateTime.now());
        siteFrame.withFrameDefaults(
                new VersionFrameDefaultsStructure()
                        .withDefaultLocale(
                                new LocaleStructure()
                                        .withTimeZone("Europe/Paris")));
        return siteFrame;
    }
}
