name: Build and push
on:
  push:
    branches:
      - master
<<<<<<< fix/publish-artifacts-with-jreleaser
  pull_request:
    branches:
      - master
=======
>>>>>>> master

env:
    JFROG_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
    JFROG_PASS: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
jobs:
  maven-package:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy maven settings
        run: |
          wget https://raw.githubusercontent.com/entur/ror-maven-settings/master/.m2/settings.xml -O .github/workflows/settings.xml
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.5+11
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Run maven build
        run: mvn package -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -s .github/workflows/settings.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: target/*.jar
  publish-release:
    name: Publish release to maven central
<<<<<<< fix/publish-artifacts-with-jreleaser
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@1.0.1
=======
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@fix-maven-publish
>>>>>>> master
    secrets: inherit
    with:
      push_to_repo: true